language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t dto80/htmltest .
- docker push dto80/htmltest
after_success:
- docker run -p 8080:80 -d dto80/htmltest:latest
service: docker
