language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t $DOCKER_USERNAME/htmltest .
- docker push $DOCKER_USERNAME/htmltest
after_success:
- docker stop htmltest
- docker rm htmltest
- docker run -p 8088:80 -d --name htmltest $DOCKER_USERNAME/htmltest:latest
service: docker
env:
  global:
  - secure: m6yXCDFymRWKoJCHHOOYBnauXCoDre5r/3g+KtZnF/kvU/bcbqeEnClRvOfOclV1uENrzFfpmuLvKhp4QT5cKo/PNvg7BP1mr10IpqA1otd3wURhSZ89rDL/RlxrHftUhpW5QhYKfDxSXbFUxRy2Ujk+5NHtljcMBb8BrAOazsVu0592AHcW8w/HZhvK9+Vs/fvmMsVEAw4TexoEhPgN1S1DmgV4+y4gORIs6gZQvjlx4zybMHOX5NNTfOub7pMtU1Wo2iQrtojwT2UYykV+NLxq/FwtSSZngSnVvpbLoxHdRg/pQsvrZtUd4DMQ3n8OwhJb2Z+XpP5WJIvoP+x2OgzXG6N81XnxOyHc7quzWC6+ORMYJaeA8BZfXdFJ7sNK9sLs/yxTuytV68FD3Pz6XgSiz4Xdxf1gFEafKC10/FBeMJgSxrxSoMiGskJ/N1DY7ZBjyc8oqyA0O7HMCaeF7hv5PXGUoYqW6L7cRnFGdm5GYLpsKRYe8XkPibP+yHErXJ9Ph/o80swfhfsnn6vfD6CK0rFt6rhjI3Kc9wnxj6jo3bw3z9bbXAYTzluvvNGbD90NrSzW3AjcgTRWdM/uK4rBJPU6vbBauaV1l1BQbV2V0BySjeRtDabu+3jiBxT7+gnd0KH7R5P/MIunKoIqIwDxakY2xe4WuWbOJ8crRZI=
  - secure: n5vx5HZP3mRnhzamR1mAlqcosv55KVKfUQJ98G8OQs8cSPaIxbjj971cBYYhEKe5sHqW1WMpmHEOyDkuLohRYTWgKVxyiPgzrzPm5XtSWesCLdS5/CSxZ9E1OGK8tNnsjK+zF2H6z1OSJpxzU32Qpef5QowLRxjxJsJM6ytp6AFEHmZuocbxxrfmwFVLVrjzOFCcv+yM+N8xuP6AZIdy2OSW7Zg0J4H3VUkgscDTQ8l3Ppv40rsWiK0aSWjv3oyPKV0sOGlhSTd2PP3Z8Av3cYfwpyPppBNBTV3QbMmpJJFnCmttUKPHDlTAR1sfB7ngMuEUJV5W/jxQEam81dS3Ps0tc/5Lf0/eO/JXmmzDI7EejU9/D21ppoJ0QhXX4vga5p3TeJjfx76moBH4Itxc4LcSLQZoJefbdk0x6RXz1/5LvliTBMEL2z6hYN/FxrsxMkIFuGRetIsTE16GCvKCKMtsExIneqre9F29vk2YDNcogjK3NFiJmKjMkEbAoPrw3FiRJHf+P+G3hUkQrtfP9ZV0l0SCbZK7vca8zcuGfDEdDM/hSkqEclOh4Zge7lJTQPTlWnucuIoRvzg4+yIq6ZEzmYzGK/p1aVHvVWWtQoy7nInyN4ZypTQ+0G8DMHDq19N3rjIAA5NGI6M4qmSh+lrhFwWAWsadNpEx3VOV0zI=
  - secure: x5K5KBYOP/BstL7lHEF411776hAruJqpUzfafHEJ20jq0jRmbfZ2I8hF2pmfDOefS80Q4iYtqE+p4HDFdB6d2Bdb6OWzk9MHCCTa3d3xSCuaakY5SSThkALP/GMubpz5cIIR+TEtsr/IDT+dN0ihUl5RCxGBVmXKj7Qps9ckaHwVw0HDcm9S5d8J07vSVIfpyP9FUiG9POL2a7LYNMMOdoE5iOFTEf+4hDebj4SPRrMibJj7/NATmvQ+kNMdqSnSDvGVN/ztCnChThbK1SqhUu+bQy1Zcn8gorEgbEi28eJzM5xeVk6yDxavzNurdVWzmOUu3y86d6VamhQnUDbQi/9FWSz4Y4rILz6KxDOinOXF+5VVoVlMlrp2LPz0TwfWsgNkxKmuyf4dL3zKeiqbImudXTU/EgaSNLdRnYr7s9fXbD32xFTlNehnEn31gQy0CynbUjrNf09+vD59rcIYqm8oDM9Rg5eJwbcqaj9cynE0lNEAdEYtaXc0X6xNPmg1LSbME/P/XvdugF15Kb3s7q4Wb6Qy3tRZE3luLpnyvQ4e5Cfeou67I/44+gBoq055ZwzGsNcpTC1fDf0cC50PwD8FCnpS15DARKzBY6uWUZR+eVp3UNXrirTO4eo7zkXHckAVr/SWKDDmmkY4CuupegGhdV3K3PZN59e9LCCWHjQ=
addons:
    ssh_knows_hosts:
    - 54.149.139.47